version: "3.7"

services:
  db:
    image: 'postgres:11'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    command: 'bundle exec rails s -b 0.0.0.0'
    working_dir: '/app'
    links:
      - 'db:database'
    image: covid19br_info:dev
    build:
      context: './docker'
      dockerfile: 'Dockerfile.dev'
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
      - 'gems-data:/usr/local/bundle'
      - 'node_modules-data:/app/node_modules'
    environment:
      WEBPACKER_DEV_SERVER_HOST: 'webpack'

  webpack:
    command: './bin/webpack-dev-server'
    working_dir: '/app'
    links:
      - 'db:database'
    image: covid19br_info:dev
    ports:
      - '3035:3035'
    volumes:
      - './:/app'
      - 'gems-data:/usr/local/bundle'
      - 'node_modules-data:/app/node_modules'
    environment:
      WEBPACKER_DEV_SERVER_HOST: '0.0.0.0'

volumes:
  postgres-data:
    driver: local
  gems-data:
    driver: local
  node_modules-data:
    driver: local
