FROM ruby:2.7-alpine3.11
ENV BUNDLE_JOBS 8
RUN apk add --no-cache \
            bash \
            build-base \
            git \
            less \
            nodejs \
            postgresql-dev \
            yarn \
            tzdata
